### Word Embedding Layers for Deep Learning with Keras

In [1]:
# Import libraries
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=['Well done!',
        'Good work',
        'Great effort',
        'nice work',
        'Excellent!',
        'Weak',
        'Poor effort!',
        'not good',
        'poor work',
        'Could have done better.']

In [4]:
sent

['Well done!',
 'Good work',
 'Great effort',
 'nice work',
 'Excellent!',
 'Weak',
 'Poor effort!',
 'not good',
 'poor work',
 'Could have done better.']

In [5]:
# Vocabulary size
voc_size = 10000

### One Hot Representation

In [6]:
 = [one_hot(word, voc_size) for word in sent]
print(onehot_repr)

[[7712, 7516], [2823, 9815], [5957, 8679], [9264, 9815], [6211], [8649], [4510, 8679], [1635, 2823], [4510, 9815], [8209, 8103, 7516, 1753]]


### Word Embedding Representation

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [9]:
sent_length=8
embedded_docs = pad_sequences(onehot_repr,padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0    0    0 7712 7516]
 [   0    0    0    0    0    0 2823 9815]
 [   0    0    0    0    0    0 5957 8679]
 [   0    0    0    0    0    0 9264 9815]
 [   0    0    0    0    0    0    0 6211]
 [   0    0    0    0    0    0    0 8649]
 [   0    0    0    0    0    0 4510 8679]
 [   0    0    0    0    0    0 1635 2823]
 [   0    0    0    0    0    0 4510 9815]
 [   0    0    0    0 8209 8103 7516 1753]]


In [12]:
dim=10

In [13]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [15]:
rint(model.predict(embedded_docs))

[[[ 0.04918827 -0.01602035 -0.00388443 -0.03553269 -0.03783156
    0.0307424   0.01999005 -0.02948978  0.03425104 -0.03649259]
  [ 0.04918827 -0.01602035 -0.00388443 -0.03553269 -0.03783156
    0.0307424   0.01999005 -0.02948978  0.03425104 -0.03649259]
  [ 0.04918827 -0.01602035 -0.00388443 -0.03553269 -0.03783156
    0.0307424   0.01999005 -0.02948978  0.03425104 -0.03649259]
  [ 0.04918827 -0.01602035 -0.00388443 -0.03553269 -0.03783156
    0.0307424   0.01999005 -0.02948978  0.03425104 -0.03649259]
  [ 0.04918827 -0.01602035 -0.00388443 -0.03553269 -0.03783156
    0.0307424   0.01999005 -0.02948978  0.03425104 -0.03649259]
  [ 0.04918827 -0.01602035 -0.00388443 -0.03553269 -0.03783156
    0.0307424   0.01999005 -0.02948978  0.03425104 -0.03649259]
  [-0.00941093  0.02213323  0.03496926 -0.03591223  0.01909688
    0.02115214  0.01042583 -0.00093273  0.00976828 -0.0424466 ]
  [-0.00368799 -0.01857704 -0.00332037  0.02986387  0.02720796
    0.02080611 -0.00100161 -0.02547325  0.045161

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0, 7712, 7516], dtype=int32)

In [17]:
print(model.predict(embedded_docs)[0])

[[ 0.04918827 -0.01602035 -0.00388443 -0.03553269 -0.03783156  0.0307424
   0.01999005 -0.02948978  0.03425104 -0.03649259]
 [ 0.04918827 -0.01602035 -0.00388443 -0.03553269 -0.03783156  0.0307424
   0.01999005 -0.02948978  0.03425104 -0.03649259]
 [ 0.04918827 -0.01602035 -0.00388443 -0.03553269 -0.03783156  0.0307424
   0.01999005 -0.02948978  0.03425104 -0.03649259]
 [ 0.04918827 -0.01602035 -0.00388443 -0.03553269 -0.03783156  0.0307424
   0.01999005 -0.02948978  0.03425104 -0.03649259]
 [ 0.04918827 -0.01602035 -0.00388443 -0.03553269 -0.03783156  0.0307424
   0.01999005 -0.02948978  0.03425104 -0.03649259]
 [ 0.04918827 -0.01602035 -0.00388443 -0.03553269 -0.03783156  0.0307424
   0.01999005 -0.02948978  0.03425104 -0.03649259]
 [-0.00941093  0.02213323  0.03496926 -0.03591223  0.01909688  0.02115214
   0.01042583 -0.00093273  0.00976828 -0.0424466 ]
 [-0.00368799 -0.01857704 -0.00332037  0.02986387  0.02720796  0.02080611
  -0.00100161 -0.02547325  0.04516197  0.02390577]]
